# permissions for end users to view samenessgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samenessgroups-viewer-role
rules:
- apiGroups:
  - consul.hashicorp.com
  resources:
  - samenessgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consul.hashicorp.com
  resources:
  - samenessgroups/status
  verbs:
  - get
