name: nightly-consul-compatibility
on:
  schedule:
    - cron: "0 0 * * *" # to debug on non main branch, replace schedule and chron with just push

jobs:

  # acceptance-consul-compatibility tests Consul version compatibility with its corresponding Conul-k8s version
  # This test downloads the latest release image of Consul-K8s and tests them against the latest development versions
  # of Consul-Enterprise
  acceptance-consul-compatibility:
    uses: ./.github/workflows/reusable-acceptance.yml
    strategy:
      matrix:
        include:
          - { runner: "Consul 1.12/K8s 0.49", kind-version: "v1.23.0", envoy-version: "envoyproxy/envoy:v1.22.2", consul-version: "1.12-dev", consul-k8s-tag: "release/0.49.x"} #TODO once v0.49.1 is released change to v0.49.1
          - { runner: "Consul 1.13/K8s 0.49", kind-version: "v1.23.0", envoy-version: "envoyproxy/envoy:v1.23.1", consul-version: "1.13-dev", consul-k8s-tag: "release/0.49.x"} #TODO once v0.49.1 is released change to v0.49.1
      fail-fast: false
    with:
      name: acceptance
      directory: acceptance/tests
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      additional-flags: "-use-kind -kubecontext=kind-dc1 -secondary-kubecontext=kind-dc2 -envoy-image=${{ matrix.envoy-version }} -consul-image=hashicorppreview/consul-enterprise:${{ matrix.consul-version }}"
      gotestsum-version: 1.8.2
      consul-k8s-image: docker.io/hashicorppreview/consul-k8s-control-plane:0.49.0 # TODO: replace with docker.io/hashicorp/consul-k8s-control-plane:0.49 once 0.49 supports actions
      kind-version: ${{ matrix.kind-version }}
      checkout-ref: ${{ matrix.consul-k8s-tag }}
    secrets:
      CONSUL_ENT_LICENSE: ${{ secrets.CONSUL_ENT_LICENSE }}